var meetup = {
    "city":{
        "id":624814,
        "city":"London",
        "lat":43.01,
        "lon":-81.18,
        "state":"ON",
        "country":"ca",
        "zip":"N5V 0A1",
        "member_count":1410
    },
    "events":[
        {
            "created":1445266131000,
            "duration":7200000,
            "id":"kqqpllyxfbdc",
            "image": "front_end_dev_meetup.jpg",
            "name":"Front-End Development Meetup",
            "status":"upcoming",
            "time":1521759600000,
            "local_date":"2018-mar-22",
            "local_time":"19:00",
            "updated":1514081304000,
            "utc_offset":-14400000,
            "waitlist_count":0,
            "yes_rsvp_count":5,
            "venue":{
                "id":24025637,
                "name":"Hacker Studios",
                "lat":42.98481369018555,
                "lon":-81.24620819091797,
                "repinned":false,
                "address_1":"252 Dundas Street",
                "city":"London",
                "country":"ca",
                "localized_country_name":"Canada",
                "zip":"",
                "state":"ON"
            },
            "group":{
                "created":1439235148000,
                "name":"London Front-end Development Meetup",
                "id":18820217,
                "join_mode":"open",
                "lat":42.97999954223633,
                "lon":-81.26000213623047,
                "urlname":"London-Front-end-Development-Meetup",
                "who":"Devs",
                "localized_location":"London, ON",
                "region":"en_US"
            },
            "link":"https://www.meetup.com/London-Front-end-Development-Meetup/events/246166695/",
            "visibility":"public"
        },
        {
            "created":1491966585000,
            "duration":10800000,
            "fee":{
                "accepts":"cash",
                "amount":10.0,
                "currency":"CAD",
                "description":"",
                "label":"Price",
                "required":false
            },
            "id":"239148427",
            "name":"World Usability Day - UX and UI",
            "image": "ladies_that_ux.jpg",
            "status":"upcoming",
            "time":1520548200000,
            "local_date":"2018-mar-08",
            "local_time":"17:30",
            "rsvp_open_offset":"PT18H",
            "updated":1519259853000,
            "utc_offset":-18000000,
            "waitlist_count":0,
            "yes_rsvp_count":12,
            "venue":{
                "id":25722974,
                "name":"The London Club",
                "lat":0.0,
                "lon":0.0,
                "repinned":false,
                "address_1":"177 Queens Ave.",
                "city":"London",
                "country":"ca",
                "localized_country_name":"Canada",
                "zip":"",
                "state":"ON"
            },
            "group":{
                "created":1453208546000,
                "name":"Ladies that UX - London Ontario",
                "id":19365592,
                "join_mode":"open",
                "lat":42.939998626708984,
                "lon":-81.20999908447266,
                "urlname":"Ladies-that-UX-London-Ontario",
                "who":"LTUXers",
                "localized_location":"London, ON",
                "region":"en_US"
            },
            "link":"https://www.meetup.com/Ladies-that-UX-London-Ontario/events/239148427/",
            "description":"<p>**IMPORTANT INFORMATION! Please register for the event at the link below - not on meetup.com!**</p> <p><a href=\"https://www.wct-fct.com/en/civicrm/event/info?reset=1&id=285\" class=\"linkified\">https://www.wct-fct.com/en/civicrm/event/info?reset=1&id=285</a></p> <p>Press For Progress is a call to motivate and unite friends, colleagues, and whole communities to think, act, and be, gender inclusive. Because we know, equipped with the right resources, today's girls and women are our future leaders, entrepreneurs, and change-makers.</p> <p>On International Women's Day, join Ladies that UX London Ontario, in partnership with the Women in Communication and Technology, The London Club Speaker Series, for an evening celebrating the unity and harmony between women, the strength of our collective voices, and why we need to continue to Press for Progress.</p> <p>Sponsored by the London Economic Development Corporation, our prestigious line-up of speakers includes award-winning spoken word artist, Holly Painter, Kate Young, Member of Parliament for London West and Parliamentary Secretary to the Minister of Science, and StarTech.com (<a href=\"http://startech.com/\" class=\"linkified\">http://startech.com/</a>) President Lynn Smurthwaite-Murphy as our keynote speaker. These incredible women will share their stories and key learnings in and out of the boardroom.</p> <p>When: March 8, 2018 (5:30-8pm)<br/>Where: The London Club, 177 Queens Ave.<br/>Cost: $10.00</p> <p>All proceeds go to Anova (<a href=\"http://www.anovafuture.org/\" class=\"linkified\">http://www.anovafuture.org/</a>). Tickets include light refreshments and entry to our door prize draw. Cash bar will be available.</p> <p>Anova provides safe places, shelter, support, counselling, and resources for abused women, their children, and all oppressed individuals to find a new start.</p> <p>Reserve your spot: Click here (<a href=\"https://www.wct-fct.com/en/civicrm/event/info?reset=1&id=285\" class=\"linkified\">https://www.wct-fct.com/en/civicrm/event/info?reset=1&id=285</a>)</p> <p>#PressForProgress presents a great opportunity to make new connections with like-minded networking groups in the Forest City.</p> <p>Agenda<br/>Event Time 5:30 - 8:00pm<br/>Registration & Networking 5:30 - 6:00pm<br/>Speaker Event 6:00 - 7:00pm<br/>Post-Event Networking 7:15 - 8:00 pm</p> <p>Thank you to our sponsors:<br/>The London Economic Development Corporation and The London Club Speaker Series</p> ",
            "visibility":"public"
        },
        {
            "created":1512176675000,
            "duration":10800000,
            "id":"245574300",
            "name":"Build a Child Theme in Wordpress",
            "image": "wordpress_london.jpg",
            "rsvp_limit":25,
            "status":"upcoming",
            "time":1521586800000,
            "local_date":"2018-mar-20",
            "local_time":"19:00",
            "updated":1519221871000,
            "utc_offset":-14400000,
            "waitlist_count":0,
            "yes_rsvp_count":9,
            "venue":{
                "id":5024132,
                "name":"London Public Library (Landon Branch in Old South)",
                "lat":42.972198486328125,
                "lon":-81.25288391113281,
                "repinned":false,
                "address_1":"167 Wortley Road",
                "city":"London",
                "country":"ca",
                "localized_country_name":"Canada",
                "zip":"",
                "state":"ON"
            },
            "group":{
                "created":1414089216000,
                "name":"WordPress London Canada",
                "id":17818122,
                "join_mode":"open",
                "lat":43.02000045776367,
                "lon":-81.20999908447266,
                "urlname":"WordPress-London",
                "who":"WordPressers",
                "localized_location":"London, ON",
                "region":"en_US"
            },
            "link":"https://www.meetup.com/WordPress-London/events/245574300/",
            "description":"<p>When you need to make modifications to the theme you are using, child themes are the way to go. We will demonstrate how to do it. If you have a site you want to try this on you can follow along. No programming experience is needed, we will cover the basics.</p> ",
            "visibility":"public",
            "pro_is_email_shared":false
        },
        {
            "created":1518895582000,
            "duration":10800000,
            "id":"247906863",
            "name":"Female Artists\u2019 Music Night at Cowboys!!",
            "image": "london_activity_group.jpg",
            "status":"upcoming",
            "time":1520121600000,
            "local_date":"2018-mar-03",
            "local_time":"19:00",
            "updated":1518963287000,
            "utc_offset":-18000000,
            "waitlist_count":0,
            "yes_rsvp_count":15,
            "venue":{
                "id":17886022,
                "name":"Cowboys Ranch",
                "lat":42.983699798583984,
                "lon":-81.26339721679688,
                "repinned":false,
                "address_1":"60 Wharncliffe Rd North",
                "city":"London",
                "country":"ca",
                "localized_country_name":"Canada",
                "zip":"",
                "state":"ON"
            },
            "group":{
                "created":1441820763000,
                "name":"London Random Activity Meetup Hosted by Infinite Activities",
                "id":18915354,
                "join_mode":"open",
                "lat":42.9900016784668,
                "lon":-81.27999877929688,
                "urlname":"Londonrandomactivitymeetup",
                "who":"Friends",
                "localized_location":"London, ON",
                "region":"en_US"
            },
            "link":"https://www.meetup.com/Londonrandomactivitymeetup/events/247906863/",
            "description":"<p>\u2022 What we'll do<br/>I will be sitting in on drums for a friend of mine, who will be one of three London, female musicians performing that night. She is a very talented musician, and I had the pleasure of performing with her at Trackside, on Canada Day, 2017.<br/>Each will play a set from 7-8pm, 8-9pm (which is the one I'm playing for) and 9-10pm.<br/>Tickets are $10 and $2 from each ticket will go towards the \"My Sister's Place\" charity.<br/>Hope to see a bunch of you out, for a fun night of music, dancing, and to support our local female music artists and a great charity!</p> <p>\u2022 What to bring</p> <p>\u2022 Important to know</p> ",
            "visibility":"public"
        }
    ]

};
